### ISSUE TITLE
Failed to compile on Ubuntu 24.04 with gcc-13

### ISSUE THREAD

**Issue by boroli** [XapaJIaMnu/translateLocally#173]
I tried to compile it under Ubuntu 24.04 with gcc-13.

It failed somewhere in the sub-3rd-parties marian-dev. Not sure if this is caused by a newer gcc version compared to Ubuntu 22.04.

```
[ 53%] Building CXX object 3rd_party/bergamot-translator/3rd_party/marian-dev/src/CMakeFiles/marian.dir/optimizers/quantizer.cpp.o
[ 55%] Building CXX object 3rd_party/bergamot-translator/3rd_party/marian-dev/src/CMakeFiles/marian.dir/microsoft/cosmos.cpp.o
In file included from /usr/lib/gcc/x86_64-linux-gnu/13/include/immintrin.h:39,
                 from /translateLocally/3rd_party/bergamot-translator/3rd_party/marian-dev/src/functional/operators.h:223,
                 from /translateLocally/3rd_party/bergamot-translator/3rd_party/marian-dev/src/functional/functional.h:7,
                 from /translateLocally/3rd_party/bergamot-translator/3rd_party/marian-dev/src/optimizers/quantizer.h:4,
                 from /translateLocally/3rd_party/bergamot-translator/3rd_party/marian-dev/src/optimizers/quantizer.cpp:3:
/usr/lib/gcc/x86_64-linux-gnu/13/include/smmintrin.h: In static member function 'static marian::float32x4 marian::functional::Ops<marian::float32x4>::round(const marian::float32x4&)':
/usr/lib/gcc/x86_64-linux-gnu/13/include/smmintrin.h:125:1: error: inlining failed in call to 'always_inline' '__m128 _mm_round_ps(__m128, int)': target specific option mismatch
  125 | _mm_round_ps (__m128 __V, const int __M)
      | ^~~~~~~~~~~~
/translateLocally/3rd_party/bergamot-translator/3rd_party/marian-dev/src/functional/operators.h:278:75: note: called from here
  278 |   static inline float32x4 round(const float32x4& x)  { return _mm_round_ps(x, _MM_FROUND_TO_NEAREST_INT); }
      |                                                               ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/13/include/smmintrin.h:125:1: error: inlining failed in call to 'always_inline' '__m128 _mm_round_ps(__m128, int)': target specific option mismatch
  125 | _mm_round_ps (__m128 __V, const int __M)
      | ^~~~~~~~~~~~
/translateLocally/3rd_party/bergamot-translator/3rd_party/marian-dev/src/functional/operators.h:278:75: note: called from here
  278 |   static inline float32x4 round(const float32x4& x)  { return _mm_round_ps(x, _MM_FROUND_TO_NEAREST_INT); }
      |                                                               ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/13/include/smmintrin.h:125:1: error: inlining failed in call to 'always_inline' '__m128 _mm_round_ps(__m128, int)': target specific option mismatch
  125 | _mm_round_ps (__m128 __V, const int __M)
      | ^~~~~~~~~~~~
/translateLocally/3rd_party/bergamot-translator/3rd_party/marian-dev/src/functional/operators.h:278:75: note: called from here
  278 |   static inline float32x4 round(const float32x4& x)  { return _mm_round_ps(x, _MM_FROUND_TO_NEAREST_INT); }
      |                                                               ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [3rd_party/bergamot-translator/3rd_party/marian-dev/src/CMakeFiles/marian.dir/build.make:1077: 3rd_party/bergamot-translator/3rd_party/marian-dev/src/CMakeFiles/marian.dir/optimizers/quantizer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:589: 3rd_party/bergamot-translator/3rd_party/marian-dev/src/CMakeFiles/marian.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```
