### ISSUE TITLE
trouble building on Mac m1

### ISSUE THREAD

**Issue by SophieDC98** [XapaJIaMnu/translateLocally#138]
I'm working on a macOS Ventura version 13.2.1 with M1 chip and I'm unable to build the package. I keep getting the following error:

`the clang compiler does not support '-march=native'`

I tried replacing the `add_compile_options(-march=${BUILD_ARCH})` with `add_compile_options(-mcpu=apple-m1)`, but I keep getting the error. Am I missing something?

my clang version is 14.0.0

**Comment by kpu** [comment]
Try changing `3rd_party/bergamot-translator/3rd_party/marian-dev/CMakeLists.txt` too.  I think should should be made an option.

**Comment by sophieDataroots** [comment]
I tried it again, but I'm prompted by the next error:
`In file included from /Users/sophiedataroots/Documents/projects/translateLocally/3rd_party/bergamot-translator/3rd_party/marian-dev/src/3rd_party/intgemm/intgemm/intgemm.cc:9:
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/cpuid.h:14:2: error: this header is for x86 only
#error this header is for x86 only`

Do I need to set a certain variable specifically for Mac m1?

**Comment by XapaJIaMnu** [comment]
Sorry about this, I'll try to check on M1 but it might be a few weeks. We have an ARM build working on ubuntu arm, and for M1 we've used `x86_64` generic prefix, which works with the rosetta stone. There seems to be an issue with how the default architecture on the clang compiler exports ARM defines.

The error you are getting shouldn't ever be there, because the submodule in question should never be compiled.

`intgemm` is compiled only if `USE_INTGEMM` is set https://github.com/browsermt/marian-dev/blob/master/src/tensors/cpu/integer_common.h#L10 , and if we detect arm, it is not: https://github.com/browsermt/marian-dev/blob/master/CMakeLists.txt#L68

`if(${CMAKE_TARGET_ARCHITECTURE_CODE} MATCHES "arm")` branch should be taken. Could you add a 
`message(${CMAKE_TARGET_ARCHITECTURE_CODE})` to the line before and see what the M1 reports here?

**Comment by sophieDataroots** [comment]
Oh weird. When you have time to test it and it works on your M1, can you send the commands you used? No worries if it takes some time :)

**Comment by jelmervdl** [comment]
I ran into this error as well when I was trying to make a universal binary for macOS Intel/ARM. I thought it was due to cpuid taking some information from cmake at compile time, which obviously doesn't work when your compiler is emitting for two architectures at the same time :(

**Comment by XapaJIaMnu** [comment]
Hmm, we are using two very different codepaths for ARM and x86 _64 here... We should at the very least allow for exclusive M1 build

**Comment by XapaJIaMnu** [comment]
Hi @SophieDC98 ,
We have identified an issue with building an universal binary which we aim to fix shortly. 

In the meantime I've pushed some fixes that should allow for building natively on M1/M2 class hardware. Instructions:
```bash
git clone https://github.com/XapaJIaMnu/translateLocally.git
cd translateLocally
mkdir build
cd build
# Optional. If you use non standard qt, export path to it: export PATH=/Users/nick/Qt/6.5.2/macos/lib/cmake/:$PATH
cmake .. -DBUILD_EXTERNAL_LIBARCHIVE=ON -DSSPLIT_USE_INTERNAL_PCRE2=ON
# Fix Ruy Build. This step is mandatory otherwise the build will fail with weird include errors
# cmake will provide the exact command you should use in the form of a warning
# it will look like:
../cmake/fix_ruy_build.sh ../ ./
make -j8
```
Let me know if you run into any errors.

**Comment by XapaJIaMnu** [comment]
Could you post your cmake log and the last bits of `make VERBOSE=1` just the part with the error?

**Comment by XapaJIaMnu** [comment]
We now provide separate M1 builds. thanks to @jelmervdl 
Steps to build are shown in the workflow file: https://github.com/XapaJIaMnu/translateLocally/blob/master/.github/workflows/build.yml#L131
